server.port: ${SERVER_PORT:8080}
spring.application.name: api-gateway

security:
  users:
    user:
      username: ${GATEWAY_USER_USERNAME:user}
      password: ${GATEWAY_USER_PASSWORD:changeit-user}
    admin:
      username: ${GATEWAY_ADMIN_USERNAME:admin}
      password: ${GATEWAY_ADMIN_PASSWORD:changeit-admin}

services:
  customer-url: ${CUSTOMER_SERVICE_URL:http://localhost:8081}
  account-url: ${ACCOUNT_SERVICE_URL:http://localhost:8082}
  transaction-url: ${TRANSACTION_SERVICE_URL:http://localhost:8083}
  compliance-url: ${COMPLIANCE_SERVICE_URL:http://localhost:8084}
  notification-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
