services:
  postgres:
    image: postgres:16-alpine
    container_name: digibank-db
    environment:
      POSTGRES_DB: digibank_db
      POSTGRES_USER: digibank_user
      POSTGRES_PASSWORD: digibank_pwd
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U digibank_user -d digibank_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - digibank-net

  wildfly:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
    container_name: digibank-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - digibank-net

networks:
  digibank-net:
    driver: bridge

volumes:
  pgdata:
