CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    description VARCHAR(500) NOT NULL,
    reference_number VARCHAR(36) NOT NULL UNIQUE,
    transaction_date TIMESTAMP NOT NULL
);
