from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


ROOT = Path(__file__).resolve().parents[4]
OUT = ROOT / "docs/devsecops/presentation/output/digibank-workshop3-dast-draft.pdf"
DIAGRAM = ROOT / "docs/devsecops/presentation/assets/diagrams/07_microservices_topology.png"
MAKE_UP = ROOT / "docs/devsecops/presentation/assets/screenshots/make-up.png"
CONTAINERS = ROOT / "docs/devsecops/presentation/assets/screenshots/containers-servies.png"
MAKE_SMOKE = ROOT / "docs/devsecops/presentation/assets/screenshots/make-smoke.png"
POSTMAN_FUNCTIONAL = ROOT / "docs/devsecops/presentation/assets/screenshots/postman-happypath.png"
POSTMAN_SECURITY = ROOT / "docs/devsecops/presentation/assets/screenshots/postmanrun-output-1.png"
POSTMAN_SECURITY_DETAIL = ROOT / "docs/devsecops/presentation/assets/screenshots/postman-run-output2.png"
SESSION = ROOT / "docs/devsecops/presentation/assets/screenshots/session-behavior.png"
HEADERS = ROOT / "docs/devsecops/presentation/assets/screenshots/information-exposure.png"
NEWMAN = ROOT / "docs/devsecops/presentation/assets/screenshots/newman-scan.png"
NEWMAN_REPORTS = ROOT / "docs/devsecops/presentation/assets/screenshots/newman-directory-result.png"
ZAP = ROOT / "docs/devsecops/presentation/assets/screenshots/zap-scan.png"
ZAP_ALERTS = ROOT / "docs/devsecops/presentation/assets/screenshots/alert-zap-scan.png"
TRIVY_FINAL = ROOT / "docs/devsecops/presentation/assets/screenshots/final-report-from-trivy.png"
TRIVY_IMAGE = ROOT / "docs/devsecops/presentation/assets/screenshots/image-scan.png"
IMAGE_SIZES = ROOT / "docs/devsecops/presentation/assets/screenshots/image-sizes.png"
MULTI_STAGE = ROOT / "docs/devsecops/presentation/assets/screenshots/multi-stage-build.png"
TRIVY_BEFORE_ACCOUNT = ROOT / "docs/devsecops/presentation/assets/screenshots/before-account-service-fix.png"
TRIVY_AFTER_ACCOUNT = ROOT / "docs/devsecops/presentation/assets/screenshots/after-account-service-fix.png"
TRIVY_BEFORE_GATEWAY = ROOT / "docs/devsecops/presentation/assets/screenshots/before-api-gatewat-fix.png"
TRIVY_AFTER_GATEWAY = ROOT / "docs/devsecops/presentation/assets/screenshots/after-api-gateway-fix.png"
TRIVY_SCAN_DETAIL = ROOT / "docs/devsecops/presentation/assets/screenshots/image-scan.png"
TRIVY_AFTER_GENERAL = ROOT / "docs/devsecops/presentation/assets/screenshots/after-fix.png"
TRIVY_AFTER_CONSTRUCTION = ROOT / "docs/devsecops/presentation/assets/screenshots/after-construction-fix.png"
SONAR = ROOT / "docs/devsecops/presentation/assets/screenshots/sonar-dashbaord.png"
SONAR_ISSUES = ROOT / "docs/devsecops/presentation/assets/screenshots/openissues-sonar.png"
JACOCO_FILES = ROOT / "docs/devsecops/presentation/assets/screenshots/jacoco-files.png"
JACOCO_GATEWAY = ROOT / "docs/devsecops/presentation/assets/screenshots/apigateway-coverage.png"
JACOCO_TRANSACTION = ROOT / "docs/devsecops/presentation/assets/screenshots/transaction-service-coverage.png"
JACOCO_COMPLIANCE = ROOT / "docs/devsecops/presentation/assets/screenshots/compliance-coverage.png"
JACOCO_CONFIG = ROOT / "docs/devsecops/presentation/assets/screenshots/config-server-coverage.png"
PIT_GATEWAY = ROOT / "docs/devsecops/presentation/assets/screenshots/PIT-test-report-api-gateway.png"
PIT_CUSTOMER = ROOT / "docs/devsecops/presentation/assets/screenshots/pit-report-customer-service.png"
PIT_DISCOVERY = ROOT / "docs/devsecops/presentation/assets/screenshots/pit-report-descovery-service.png"
DEPENDENCY_CHECK = ROOT / "docs/devsecops/presentation/assets/screenshots/dependency-check.png"
NIST_AUTHORITY = ROOT / "docs/devsecops/presentation/assets/screenshots/nist-authority.png"
NVD_RUN = ROOT / "docs/devsecops/presentation/assets/screenshots/nvd-run.png"


styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="CoverKicker", parent=styles["Normal"], fontSize=9, leading=12, textColor=colors.HexColor("#555555"), spaceAfter=16, tracking=1.5))
styles.add(ParagraphStyle(name="CoverTitle", parent=styles["Title"], fontSize=28, leading=31, spaceAfter=12))
styles.add(ParagraphStyle(name="CoverLead", parent=styles["Normal"], fontSize=15, leading=21, spaceAfter=9))
styles.add(ParagraphStyle(name="IntroBody", parent=styles["BodyText"], fontSize=12, leading=18, spaceAfter=13))
styles.add(ParagraphStyle(name="H2Black", parent=styles["Heading2"], fontSize=18, leading=22, textColor=colors.black, spaceBefore=10, spaceAfter=8, borderPadding=3))
styles.add(ParagraphStyle(name="BodyBlack", parent=styles["BodyText"], fontSize=10.5, leading=15, spaceAfter=7))
styles.add(ParagraphStyle(name="SmallGray", parent=styles["BodyText"], fontSize=8.5, leading=11, textColor=colors.HexColor("#555555"), spaceAfter=6))
styles.add(ParagraphStyle(name="TableHeader", parent=styles["BodyText"], fontSize=9.5, leading=12, textColor=colors.white, spaceAfter=0))
styles.add(ParagraphStyle(name="Callout", parent=styles["BodyText"], fontSize=10.5, leading=15, leftIndent=8, borderColor=colors.black, borderWidth=1, borderPadding=8, backColor=colors.HexColor("#eeeeee"), spaceBefore=8, spaceAfter=10))
styles.add(ParagraphStyle(name="CodeBlock", parent=styles["Code"], fontSize=8.5, leading=12, textColor=colors.white, backColor=colors.black, borderPadding=9, spaceBefore=7, spaceAfter=10))

SECTION_GAP = Spacer(1, 6 * mm)


def P(text, style="BodyBlack"):
    return Paragraph(text, styles[style])


def table(rows, widths):
    converted = [[P(str(cell), "TableHeader" if row == 0 else "SmallGray") for cell in r] for row, r in enumerate(rows)]
    t = Table(converted, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.black),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#999999")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


story = []
story += [Spacer(1, 62 * mm), P("UCC 152-2 - Introduction to Security in DevOps", "CoverKicker"), P("DigiBank Dynamic Security Analysis", "CoverTitle"), P("Runtime security validation of the DigiBank API.", "CoverLead"), PageBreak()]

story += [P("1. Why DAST is needed", "H2Black"), P("Static analysis examines source code and configuration before execution. Dynamic analysis complements it by interacting with the application while it is running. This matters because a system can compile, pass unit tests, and still expose an API route without authentication, return excessive technical detail, accept invalid input, or handle sessions incorrectly.", "IntroBody"), P("<b>DAST checks what an external client can actually observe, not only what the source code appears to intend.</b>", "IntroBody"), P("The sequence is: establish runtime behavior, identify security weaknesses, apply targeted remediation, and replay the same scenarios to demonstrate the result.", "IntroBody"), PageBreak()]

story += [P("2. Application under test", "H2Black"), P("The external client does not call each business service directly. The API Gateway is the security boundary and the single entry point for the business API. Behind it, the customer, account, transaction, compliance, and notification services run as separate Compose services."), Image(str(DIAGRAM), width=175 * mm, height=85 * mm), P("Figure 1. Runtime topology under test: gateway, business services, platform services, Compose host and persistence boundaries.", "SmallGray"), table([["Surface", "What is tested"], ["Gateway", "Authentication, authorization, headers, cache behavior, error responses and route protection."], ["Business APIs", "Customer, account, transaction and compliance operations through gateway routing."], ["Runtime behavior", "Malformed requests, invalid values, missing resources, session behavior and information disclosure."], ["Delivery path", "Build, Compose startup, readiness, Newman replay and ZAP scanning."]], [42 * mm, 130 * mm]), PageBreak()]

story += [P("3. Reproducible test environment", "H2Black"), P("The environment is deliberately reproducible. Maven verifies the implementation, Docker Compose starts the complete topology, smoke checks verify the endpoints, and stack validation confirms that the expected containers are running before DAST begins."), P("<font name='Courier'>make clean<br/>make build<br/>make image-build<br/>make up<br/>make smoke<br/>make validate-stack<br/>make newman-scan<br/>make zap-scan</font>"), SECTION_GAP]

story += [P("3.1 Starting the application", "H2Black"), P("The Compose startup creates the complete local runtime. The screenshot shows the command used to start the services and the resulting container state. This establishes the execution context before any security request is sent."), Image(str(MAKE_UP), width=175 * mm, height=56 * mm), P("The container view confirms that the gateway, business services, databases, discovery server and config server are present in the same runtime topology.", "SmallGray"), Image(str(CONTAINERS), width=175 * mm, height=66 * mm), PageBreak()]

story += [P("3.2 Smoke validation", "H2Black"), P("Smoke validation checks the public health endpoint, gateway business routes, direct internal service endpoints, discovery registry and config server. It is not the security campaign; it proves that the application is alive and that later DAST failures can be interpreted as application behavior rather than startup failure."), Image(str(MAKE_SMOKE), width=175 * mm, height=100 * mm), P("The successful result is the gate before Newman and ZAP.", "SmallGray"), PageBreak()]

story += [P("4. Baseline and remediation decision", "H2Black"), P("The baseline establishes the behavior before the gateway security boundary was introduced. The important observations were unauthenticated business routes, no gateway role distinction, incomplete response hardening, and no explicit cache policy for sensitive API responses."), P("The remediation uses stateless HTTP Basic authentication at the gateway because it is simple to reproduce in the workshop and preserves the existing service topology. It is not presented as the production identity architecture."), table([["Request condition", "Expected result after remediation"], ["No credentials or invalid credentials", "401 Unauthorized"], ["Valid USER on normal banking API", "Request is permitted"], ["Valid USER on compliance API", "403 Forbidden"], ["Valid ADMIN on compliance API", "Request is permitted"], ["Authenticated request", "No server session or session cookie"]], [70 * mm, 102 * mm]), PageBreak()]

story += [P("4.1 Authentication and authorization in Postman", "H2Black"), P("The security collection makes the access rules visible through actual requests. The run shows unauthenticated requests returning 401, normal USER access returning 200, USER access to compliance returning 403, and ADMIN access to compliance returning 200."), Image(str(POSTMAN_SECURITY), width=175 * mm, height=126 * mm), P("The request results correspond directly to the gateway rules: authentication establishes identity, and authorization decides whether that identity may use the route.", "SmallGray"), PageBreak()]

story += [P("4.2 Validation, errors and information exposure", "H2Black"), P("The security collection also checks malformed JSON and missing resources. These cases return controlled 4xx responses without stack traces or internal implementation details. The same collection verifies the response headers on the health endpoint."), Image(str(POSTMAN_SECURITY_DETAIL), width=175 * mm, height=126 * mm), P("The run shows the validation and error-handling assertions passing, including the controlled 400 and 404 responses.", "SmallGray"), PageBreak()]

story += [P("4.3 Headers and stateless behavior", "H2Black"), P("The headers check verifies browser and response protections. The session check verifies that an authenticated request does not create a server session or return a session cookie."), Image(str(HEADERS), width=130 * mm, height=67 * mm), Image(str(SESSION), width=130 * mm, height=83 * mm), P("These screenshots show the two related controls: hardened responses and stateless authentication.", "SmallGray"), PageBreak()]

story += [P("5. Runtime checks and scan results", "H2Black"), P("Newman expresses the expected security behavior as repeatable assertions. The security collection is divided into authentication, authorization, functional regression, input validation, error handling, information exposure, session behavior, and remediation verification."), table([["Campaign", "Result"], ["Functional Newman collection", "24 requests, 74 assertions, 0 failures."], ["Security Newman collection", "12 requests, 19 assertions, 0 failures."], ["OWASP ZAP baseline", "65 passing rules, 0 failures, 2 documented warnings."]], [65 * mm, 107 * mm]), P("The two ZAP warnings are interpreted against the local workshop environment: public non-storable resources and the plain-HTTP authentication observation. Authenticated API responses receive <font name='Courier'>Cache-Control: no-store, private</font>.", "BodyBlack"), SECTION_GAP]

story += [P("5.1 Functional regression in Postman", "H2Black"), P("The functional collection checks the banking flows after the security changes: customer creation and retrieval, account creation, transactions and compliance operations. This confirms that the gateway protection did not break normal application behavior."), Image(str(POSTMAN_FUNCTIONAL), width=175 * mm, height=126 * mm), P("The collection run shows the banking requests and their passing assertions in the local environment.", "SmallGray"), PageBreak()]

story += [P("5.2 Newman security replay", "H2Black"), P("Newman repeats the same security collection without relying on the Postman interface. The summary is the reproducible command-line result used locally and in CI."), Image(str(NEWMAN), width=175 * mm, height=128 * mm), P("The security replay completed 12 requests and 19 assertions with zero failures.", "SmallGray"), Image(str(NEWMAN_REPORTS), width=150 * mm, height=42 * mm), P("The report directory contains separate functional and security JSON results.", "SmallGray"), PageBreak()]

story += [P("5.3 OWASP ZAP scan", "H2Black"), P("ZAP scans the externally visible gateway surface and complements the targeted Postman assertions. The scan checks the running application for observable response, header and authentication weaknesses that are not covered by a small set of targeted requests."), P("The current scan completed with zero failures and 65 passing rules. Two warnings remain: public non-storable resources and the local plain-HTTP authentication observation. They are reviewed against the local test environment rather than treated as an unexplained score."), SECTION_GAP]

story += [P("5.4 ZAP alert summary", "H2Black"), P("The ZAP summary reports zero High alerts, one Medium alert, zero Low alerts and one Informational alert. The remaining Medium alert is the local plain-HTTP warning associated with HTTP Basic authentication. It is recorded and explained in the report."), Image(str(ZAP_ALERTS), width=175 * mm, height=87 * mm), PageBreak()]

story += [P("5.5 Workshop 3 runtime validation", "H2Black"), P("Workshop 3 validates the same security improvements against the running Docker Compose system. The sequence is intentional: rebuild the services, start the complete topology, verify readiness, replay normal and hostile HTTP scenarios, then compare the results with the earlier findings."), table([["Runtime point", "What the validation demonstrates"], ["Authentication", "Missing and invalid credentials are rejected with 401."], ["Authorization", "USER and ADMIN roles receive different access decisions."], ["Validation and errors", "Malformed and invalid requests return controlled 4xx responses without internal details."], ["Session and headers", "No session cookie is created and required response protections are present."], ["Regression", "Customer, account, transaction and compliance routes remain usable."]], [48 * mm, 124 * mm]), P("This is runtime evidence of the remediation, not another source-code review: the result is observed at the same gateway boundary used by an external client.", "SmallGray"), PageBreak()]

story += [P("6. CI validation", "H2Black"), P("The CI workflow repeats the same validation chain after the application is built. Each step has a clear purpose: start the runtime, prove readiness, verify the exposed routes, replay the security assertions, and scan the gateway surface."), table([["Pipeline step", "Purpose"], ["Build and tests", "Compile the services and run the automated test suite."], ["Compose and readiness", "Start the complete runtime and wait for the required endpoints."], ["Smoke validation", "Confirm gateway, business APIs and platform services respond."], ["Newman", "Run the versioned functional and security request assertions."], ["ZAP", "Run an independent baseline scan against the running gateway."], ["Report upload", "Keep Newman and ZAP results available when a check fails."]], [55 * mm, 117 * mm]), P("Newman and ZAP remain separate checks: Newman verifies expected security behavior, while ZAP performs broader automated observations of the exposed HTTP surface.", "SmallGray"), SECTION_GAP]

story += [P("7. Static security analysis", "H2Black"), P("Workshop 2 moves security checks earlier in the delivery lifecycle. Instead of waiting until the application is running, the source code, dependencies and test strength are inspected during the build. SonarCloud provides code and security analysis, JaCoCo supplies test coverage data, and PITest measures whether tests detect deliberately introduced defects."), P("The analysis is applied to the current Java 21 Spring Boot microservices implementation. It does not replace the Newman and ZAP runtime checks; it complements them.", "BodyBlack"), Image(str(SONAR), width=175 * mm, height=112 * mm), P("SonarCloud quality gate passed. The dashboard reports 33.2% overall coverage, 2.8% duplication and 30 open issues.", "SmallGray"), PageBreak()]

story += [P("7.1 SonarCloud findings and decisions", "H2Black"), P("The open-issues view identified two security issues. The CSRF warning is an intentional decision for this workshop because the gateway uses stateless HTTP Basic authentication and does not create browser sessions or cookies. The URL-construction warning was treated as a real issue and remediated by encoding gateway path variables before forwarding them to downstream services."), Image(str(SONAR_ISSUES), width=175 * mm, height=118 * mm), P("Informational timestamp findings using LocalDateTime.now() are recorded as a maintainability follow-up. They do not represent an authorization, injection or secret-exposure defect.", "SmallGray"), PageBreak()]

story += [P("7.2 JaCoCo coverage evidence", "H2Black"), P("JaCoCo records which production lines are exercised by the automated tests. The report is generated during Maven verify and is imported by SonarCloud. Coverage is evidence about test reach; it is not the same as proving that the tests detect incorrect behavior."), Image(str(JACOCO_FILES), width=175 * mm, height=52 * mm), Image(str(JACOCO_GATEWAY), width=85 * mm, height=58 * mm), Image(str(JACOCO_TRANSACTION), width=85 * mm, height=58 * mm), Image(str(JACOCO_COMPLIANCE), width=85 * mm, height=58 * mm), Image(str(JACOCO_CONFIG), width=85 * mm, height=58 * mm), P("Coverage reports are available for the tested services. The notification service has no test sources and therefore produces no execution data.", "SmallGray"), PageBreak()]

story += [P("7.3 PITest mutation testing", "H2Black"), P("PITest changes compiled bytecode in controlled ways, such as negating a condition or replacing a return value. A killed mutant means a test detected the change. A surviving or uncovered mutant identifies a branch where the current tests are not strong enough to detect that behavior change."), Image(str(PIT_GATEWAY), width=175 * mm, height=74 * mm), P("The gateway report generated 34 mutations, killed 4, and recorded 24% test strength. This is a test-strength observation, not a failed scan.", "SmallGray"), Image(str(PIT_CUSTOMER), width=85 * mm, height=72 * mm), Image(str(PIT_DISCOVERY), width=85 * mm, height=72 * mm), P("The other service reports show that mutation results are module-specific; they should be reviewed as test-improvement input rather than combined into one misleading score.", "SmallGray"), PageBreak()]

story += [P("7.4 Static-analysis delivery controls", "H2Black"), P("Static checks are exposed through simple Make commands so the instructor and the team can reproduce the same controls locally."), P("<font name='Courier'>make build<br/>make sast-sonar<br/>make sast-pitest<br/>make sast-dependency-check</font>"), P("The CI workflow runs SonarCloud as a separate job, runs Dependency-Check and PITest in the static-analysis job, uploads reports even when a scan fails, and caches the Dependency-Check NVD database. The first NVD database download is large; later runs reuse the GitHub Actions cache and retrieve only updates."), table([["Control", "Evidence and decision"], ["SonarCloud", "Quality gate passed; issues reviewed and classified."], ["JaCoCo", "Coverage generated and imported into SonarCloud."], ["PITest", "Mutation reports generated; surviving mutants become test-strength follow-up."], ["Dependency-Check", "NVD report generated; zero unsuppressed CVEs after the Tomcat patch and reviewed false-positive rules."], ["CI", "Separate jobs, secret-based credentials, report upload and cache reuse."]], [45 * mm, 127 * mm])]
story += [P("7.5 Dependency-Check results", "H2Black"), P("The NVD update completed and the dependency scan generated HTML and JSON reports. The initial API Gateway report contained 43 unique CVE identifiers. After upgrading Spring Boot to 4.1.1, overriding embedded Tomcat to 11.0.25 and rerunning the scan, no unsuppressed CVEs remain across the nine Maven projects. Two dependency matches were confirmed as false positives and are covered by narrowly scoped suppression rules."), Image(str(NVD_RUN), width=82 * mm, height=57 * mm), Image(str(DEPENDENCY_CHECK), width=82 * mm, height=69 * mm), P("The captured NVD run shows the completed update, while the Dependency-Check report shows the scan output. The NIST source reference is retained as supporting context for the vulnerability database used by the scan.", "SmallGray"), Image(str(NIST_AUTHORITY), width=175 * mm, height=73 * mm), P("The false-positive decisions are explicit: Angus Activation was matched to a Jakarta Mail SMTP issue, and Hibernate Validator was matched to the unrelated Nu Html Checker issue. The suppression file is versioned and limited to those CVE/component combinations.", "BodyBlack"), table([["Result", "Decision"], ["NVD data", "Successfully updated and reused from the local/CI cache."], ["Report formats", "HTML and JSON generated for the parent and service modules."], ["OSS Index", "Disabled because the unauthenticated endpoint returned HTTP 401."], ["Before remediation", "43 unique API Gateway CVEs: 15 Critical, 13 High, 14 Medium, 1 Low."], ["After remediation", "Zero unsuppressed CVEs after Tomcat 11.0.25 and reviewed false-positive rules."], ["Evidence", "dependency-check-report.html, dependency-check-report.json and dependency-check-suppressions.xml."]], [43 * mm, 129 * mm])]
story += [P("7.6 Workshop 2 completion status", "H2Black"), P("The static-analysis setup is operational and reproducible. SonarCloud with JaCoCo, PITest, Dependency-Check, Maven verification and CI report-upload controls have all been executed. The justified code remediation identified by SonarCloud was applied, and the dependency baseline now has zero unsuppressed CVEs after the Tomcat patch and reviewed false-positive decisions."), P("Workshop 2 is complete as a documented analysis and remediation exercise. PITest surviving mutants remain test-strength follow-up items, not unresolved dependency vulnerabilities; the reports preserve them for future test improvement.", "BodyBlack")]

story += [P("8. Deliverable mapping", "H2Black"), table([["Objective", "Demonstrated by"], ["A2.1-A2.2", "SAST/Shift Left explanation and source-security review scope."], ["A2.3", "Review of validation, information exposure, dependency and test-strength risks."], ["A2.4", "Maven, SonarCloud, JaCoCo, PITest, Dependency-Check and GitHub Actions."], ["A2.5", "SonarCloud findings interpreted as remediation, accepted decision or follow-up."], ["A2.6-A2.7", "Gateway path hardening, PITest configuration fix and documented security decisions."], ["A2.8", "Passing build/tests, runtime DAST evidence and reproducible static-analysis controls."], ["A3.1-A3.8", "Workshop 1 Newman/ZAP report and runtime evidence retained in this continuation PDF."]], [35 * mm, 137 * mm]), P("<b>The result is a documented chain from source and dependency analysis, to risk interpretation, to remediation, to runtime revalidation.</b>")]

story += [PageBreak(), P("Workshop 3: Dynamic Security Analysis", "H2Black"), P("This section continues the static-analysis and remediation work with validation against the running DigiBank microservices implementation. DAST observes the behavior visible to an external client; it does not replace the source and dependency analysis already documented above."), P("Workshop 2 answered: what weaknesses can be found in the source, dependencies, configuration and tests? Workshop 3 answers: after those weaknesses are fixed, does the running application actually enforce the intended behavior without breaking valid banking flows? A fix can be incorrectly wired, applied to only one route or behave differently after deployment, so runtime revalidation is required.", "BodyBlack"), Image(str(DIAGRAM), width=175 * mm, height=78 * mm), P("The API Gateway is the runtime security boundary. All business requests in the campaign enter through this boundary before reaching the internal services.", "SmallGray"), PageBreak()]

story += [P("Workshop 3: Campaign and evidence", "H2Black"), P("The campaign combines manual scenario design in Postman, repeatable Newman assertions and an independent OWASP ZAP scan. The same categories are checked after remediation: authentication, authorization, input validation, error handling, information exposure, session behavior, headers and functional regression."), Image(str(POSTMAN_SECURITY), width=85 * mm, height=62 * mm), Image(str(POSTMAN_SECURITY_DETAIL), width=85 * mm, height=62 * mm), P("The Postman results show the expected access decisions and controlled responses. Missing credentials return 401, insufficient roles return 403, and malformed or unknown requests return controlled 4xx responses.", "SmallGray"), Image(str(NEWMAN), width=175 * mm, height=105 * mm), P("Newman provides the repeatable command-line validation used locally and in CI.", "SmallGray"), PageBreak()]

story += [P("Workshop 3: Revalidation result", "H2Black"), table([["Validation point", "Final result"], ["Functional regression", "24 requests, 74 assertions, 0 failures."], ["Security campaign", "12 requests, 19 assertions, 0 failures."], ["Authentication", "Missing and invalid credentials return 401."], ["Authorization", "USER is denied protected compliance access; ADMIN is accepted."], ["Input and errors", "Malformed and invalid requests return controlled 4xx responses without internal details."], ["Session behavior", "No session cookie is created."], ["ZAP", "65 passing rules, 0 failures, 2 documented local warnings."]], [55 * mm, 117 * mm]), Image(str(ZAP_ALERTS), width=175 * mm, height=87 * mm), P("The remaining ZAP warnings are documented local observations: public non-storable resources and the plain-HTTP authentication limitation. They are not evidence of an authentication bypass or cacheable authenticated banking responses.", "SmallGray"), P("Workshop 3 is complete when the same runtime scenarios pass after remediation and the remaining scanner observations have an explicit technical decision.", "BodyBlack")]

story += [PageBreak(), P("Workshop 4: Container and dependency security", "H2Black"), P("Workshop 4 extends the previous work from source and runtime behavior to the artifacts that are actually built and executed. The question is whether the delivered images, dependencies, configuration and packaging introduce risks that are not visible from application tests alone."), P("The current Java 21 microservices implementation uses multi-stage Dockerfiles. Maven and the JDK are used in the build stage, while the final runtime image contains only the packaged service JAR and Java runtime. Trivy checks the resulting images, the Compose configuration and the repository filesystem.", "BodyBlack"), Image(str(MULTI_STAGE), width=175 * mm, height=85 * mm), P("The multi-stage build keeps build tooling out of the runtime artifact.", "SmallGray"), PageBreak()]

story += [P("Workshop 4: Findings and remediation", "H2Black"), P("The first image scan found five High Alpine package findings in account-service and eight High findings from the unrelated pebble utility present in the Ubuntu runtime layers of the gateway, discovery and config services. The Java application layers were clean. The focused remediation changed the runtime images to the Alpine Java 21 image, updated Alpine packages and removed the unrelated utility. All service images also run as the non-root digibank user."), Image(str(TRIVY_BEFORE_ACCOUNT), width=85 * mm, height=62 * mm), Image(str(TRIVY_AFTER_ACCOUNT), width=85 * mm, height=62 * mm), Image(str(TRIVY_BEFORE_GATEWAY), width=85 * mm, height=62 * mm), Image(str(TRIVY_AFTER_GATEWAY), width=85 * mm, height=62 * mm), P("The before-and-after evidence shows that the remediation addressed container-layer findings rather than changing business code or hiding scanner results.", "SmallGray"), PageBreak()]

story += [P("Workshop 4: Final artifact validation", "H2Black"), P("The final scan covers all eight application images and the Docker Compose configuration. Each image reports zero vulnerabilities, zero Java archive findings and no detected secrets. Compose reports zero misconfigurations and zero secrets. The repository filesystem scan reports no High or Critical findings and no secrets; it retains eight Low DS-0026 observations because the Dockerfiles do not declare individual HEALTHCHECK instructions. Those remain visible as an accepted low-risk observation because Compose checks and smoke validation provide readiness evidence."), Image(str(TRIVY_FINAL), width=175 * mm, height=78 * mm), Image(str(IMAGE_SIZES), width=175 * mm, height=70 * mm), P("The final report and image-size evidence show the clean scan result and the delivered artifact inventory.", "SmallGray"), PageBreak()]

story += [P("Workshop 4: Supporting scan evidence", "H2Black"), P("These supporting captures show the scan output used to make the remediation decision. They are included as the original PNG assets; the PDF layout scales their display area for the page but does not replace them with a lower-resolution redraw."), Image(str(TRIVY_SCAN_DETAIL), width=175 * mm, height=82 * mm), Image(str(TRIVY_AFTER_GENERAL), width=175 * mm, height=82 * mm), Image(str(TRIVY_AFTER_CONSTRUCTION), width=175 * mm, height=55 * mm), P("The screenshots are read together with the generated JSON and SARIF reports, which remain the authoritative machine-readable evidence.", "SmallGray"), PageBreak()]

story += [P("Workshop 4: Deliverable mapping", "H2Black"), table([["Objective", "Evidence"], ["A4.1", "Dependency, image-layer and container-configuration risks are explained."], ["A4.2", "Dockerfiles, Compose, Maven POMs, images and CI workflow are inventoried."], ["A4.3", "Dependency-Check and Trivy analyze declared, transitive and image dependencies."], ["A4.4", "Multi-stage Dockerfiles, runtime bases, image contents and Compose parameters are reviewed."], ["A4.5", "Dependency updates, Alpine package updates, image reduction and non-root execution are applied."], ["A4.6", "Each remediation is connected to its risk reduction and verified by a new scan."], ["A4.7", "GitHub Actions rebuilds images, runs container-scan and uploads JSON/SARIF reports."], ["A4.8", "The report, screenshots, generated reports and reproducible commands document the final result."]], [35 * mm, 137 * mm]), P("Workshop 4 completes the delivery-artifact security chain: the application is analyzed, the runtime is validated, and the images and configuration used to deliver it are scanned and documented.", "BodyBlack")]


story += [PageBreak(), P("Workshop 4: Securing Containers, Dependencies, and Deployment Artifacts", "H2Black"), P("This workshop examines the artifacts that package and deliver DigiBank. Workshop 2 analyzed source code and dependencies; Workshop 3 validated the running HTTP system; Workshop 4 now checks the container images, Dockerfiles, Compose configuration, repository files and CI controls used to build and execute the system.", "BodyBlack"), P("The implementation is the current Java 21 Spring Boot microservices topology. The assignment source contains older Java 17 and monolith assumptions, so the evidence here is mapped to the actual microservices repository and its Docker Compose delivery model.", "BodyBlack"), table([["Artifact under review", "Security question"], ["Maven POMs and transitive dependencies", "Are known vulnerable components included in the build?"], ["Dockerfiles and runtime images", "Does the final image contain unnecessary tools, vulnerable packages or excessive privileges?"], ["Compose configuration", "Are ports, networks, credentials, health checks and service boundaries intentional?"], ["Repository and CI workflow", "Are secrets and configuration risks detected automatically before delivery?"]], [58 * mm, 114 * mm]), PageBreak()]

story += [P("Workshop 4: Findings, hardening and final validation", "H2Black"), P("The first Trivy image scan found five High Alpine package findings in account-service and eight High findings from the unrelated pebble utility in the Ubuntu runtime layers of the gateway, discovery and config services. The Java application layers were clean. The focused remediation moved the runtime images to Java 21 Alpine, updated Alpine packages, removed the unrelated utility and configured every service to run as the non-root digibank user."), Image(str(TRIVY_SCAN_DETAIL), width=175 * mm, height=78 * mm), Image(str(TRIVY_FINAL), width=175 * mm, height=78 * mm), P("The final scan covered all eight application images: zero vulnerabilities, zero Java archive findings and zero detected secrets. Compose reported zero misconfigurations and zero secrets. The filesystem scan reported no High or Critical findings and no secrets. Its eight Low DS-0026 observations, caused by Dockerfiles without individual HEALTHCHECK instructions, remain visible and documented; Compose, smoke and stack validation provide the readiness checks used in this educational deployment.", "SmallGray"), PageBreak()]

story += [P("Workshop 4: Deliverables A4.1-A4.8", "H2Black"), table([["Objective", "Demonstrated by"], ["A4.1", "Risks in dependencies, image layers and container configuration are explained."], ["A4.2", "Dockerfiles, Compose, Maven POMs, images, environment configuration and CI workflow are inventoried."], ["A4.3", "Dependency-Check and Trivy analyze declared, transitive and image-embedded components."], ["A4.4", "Multi-stage Dockerfiles, runtime bases, image contents, ports and runtime parameters are reviewed."], ["A4.5", "Dependency updates, Alpine package updates, image reduction and non-root execution are applied."], ["A4.6", "Each remediation is connected to its risk reduction and verified by post-remediation scanning."], ["A4.7", "GitHub Actions rebuilds images, runs container-scan and uploads JSON/SARIF reports."], ["A4.8", "The report, screenshots, generated reports and reproducible commands provide the final deliverable."]], [35 * mm, 137 * mm]), Image(str(MULTI_STAGE), width=175 * mm, height=72 * mm), Image(str(IMAGE_SIZES), width=175 * mm, height=65 * mm), P("Workshop 4 completes the delivery-artifact security chain: application analysis, runtime validation, container hardening and automated artifact verification.", "BodyBlack")]

def footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(colors.black)
    canvas.setLineWidth(1)
    canvas.line(17 * mm, 13 * mm, 193 * mm, 13 * mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#555555"))
    canvas.drawString(17 * mm, 8 * mm, "DigiBank - Dynamic Security Analysis")
    canvas.drawRightString(193 * mm, 8 * mm, str(doc.page))
    canvas.restoreState()


doc = SimpleDocTemplate(str(OUT), pagesize=A4, rightMargin=17 * mm, leftMargin=17 * mm, topMargin=17 * mm, bottomMargin=20 * mm)
doc.build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT)
