CREATE TABLE compliance_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    check_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    checked_by VARCHAR(50) NOT NULL,
    remarks TEXT,
    check_date TIMESTAMP NOT NULL
);
